### ISSUE TITLE
punch not compiled to exe on windows

### ISSUE THREAD

**Issue by jobec** [lgiordani/punch#11]
When installing punch via pip on windows, there is no executable in the ``Scripts`` directory. Hence you cannot just run
```
punch --init
```
You need to run something like this to get it working.
```
python .venv\Scripts\punch --init
```

**Comment by jobec** [comment]
Switching to an ``entry_points`` setting in ``setup.py`` should fix this across platforms.

cfr: https://github.com/peritus/bumpversion/blob/00d121468e7e753b8c05f256ea0cfb759b805226/setup.py#L22

**Comment by lgiordani** [comment]
Thank you, I will check ASAP. Feel free to submit a PR if you have the opportunity to test it on Windows.

**Comment by jobec** [comment]
Here you go: #12

**Comment by lgiordani** [comment]
Merged and released! You can find your change in version `1.3.2`. Thanks!
