### ISSUE TITLE
no quotes when saving values from value_list

### ISSUE THREAD

**Issue by jamesj2** [lgiordani/punch#18]
I'm testing out the punch tool for my project.  I'm getting a syntax errors when trying to bump a version for the "SemVer with prerelease metadata" example.  I'm using a windows box running version 1.4.0 of punch.py installed via pip.   

Example with 'prerelease =' in punch_config.py.

> PS C:\Users\james\Documents\test> punch --part patch
> Traceback (most recent call last):
>   File "C:\Python27\Scripts\punch-script.py", line 11, in <module>
>     load_entry_point('punch.py==1.4.0', 'console_scripts', 'punch')()
>   File "c:\python27\lib\site-packages\punch\cli.py", line 149, in main
>     current_version = ver.Version.from_file(args.version_file, config.version)
>   File "c:\python27\lib\site-packages\punch\version.py", line 79, in from_file
>     version_module = import_file(version_filepath)
>   File "c:\python27\lib\site-packages\punch\helpers.py", line 8, in import_file
>     module = imp.load_source("punch_config", filepath)
>   File "punch_version.py", line 4
>     prerelease =
>                 ^
> SyntaxError: invalid syntax

Example with 'prerelease = alpha' in punch_config.py.

> Traceback (most recent call last):
>   File "C:\Python27\Scripts\punch-script.py", line 11, in <module>
>     load_entry_point('punch.py==1.4.0', 'console_scripts', 'punch')()
>   File "c:\python27\lib\site-packages\punch\cli.py", line 149, in main
>     current_version = ver.Version.from_file(args.version_file, config.version)
>   File "c:\python27\lib\site-packages\punch\version.py", line 79, in from_file
>     version_module = import_file(version_filepath)
>   File "c:\python27\lib\site-packages\punch\helpers.py", line 8, in import_file
>     module = imp.load_source("punch_config", filepath)
>   File "punch_version.py", line 4, in <module>
>     prerelease = alpha
> NameError: name 'alpha' is not defined

Now if I add quotes around alpha it works until I tried it a second time.  It gets written without any quotes.

Thanks!

**Comment by lgiordani** [comment]
Hi! Yes the last version has some issues with quotes. There is already a PR with a solution, I will merge it soon. Perhaps in the meanwhile try to use a 1.3.x version that shouldn't be affected by the problem (I think). Thanks for the issue report

**Comment by lgiordani** [comment]
Could you perhaps post your `punch_config.py` and `punch_version.py`? Thanks

**Comment by lgiordani** [comment]
Hi! Can you check if version 1.4.1 solves your issue? Thanks

**Comment by lgiordani** [comment]
As I have no further details on this issue I'll consider it solved in version 1.4.1. Actually it seems that the problem was the same that was addressed in other recent issues, and that was solved in that version. If you still have problems feel free to open another issue and to post your configuration. Thanks
