### ISSUE TITLE
Add 'remove' action and multiple actions in sequence

### ISSUE THREAD

**Issue by Daenyth** [lgiordani/punch#19]
I'd like for punch to support this workflow:

```python
'serializer': "{{date}}.{{build}}{{'b{}'.format(beta) if beta}}"
VERSION = [
    {
        'name': 'date',
        'type': 'date',
        'fmt': '%Y%m%d'
    },
    {
        'name': 'build',
        'type': 'integer',
        'start_value': 1
    },
    {
        'name': 'beta',
        'type': 'integer',
        'start_value': 0
    }
]
```

And then I'd like to have two actions:
- release
  - refresh date
  - conditional reset/increment build
  - set beta = None
- beta
  - refresh date
  - conditional reset/increment build
  - conditional reset/increment beta

---

I propose to implement it like this:
Extend `conditional_reset` with a `fields` key, (`field` xor `fields` must be present). It behaves as `field` but checks multiple fields in order.
eg
```
        'type': 'conditional_reset',
        'fields': ['build', 'beta],
        'update_fields': ['date']
    },
```
Add `remove` action that sets a part to None
eg
```
'type': 'remove',
'field': 'beta'
```
Add a `multi` action that runs multiple other action types in sequence
eq
```
'type': 'multi',
'actions': [
  {'type': 'conditional_reset',
   'field': 'build'
   'update_fields': ['date']},
  {'type': 'remove',
   'field': 'beta'}]
```

---

Would you accept a PR implementing that design? Any feedback on the approach?

**Comment by Daenyth** [comment]
I think remove might be better as a general `set_part` action with a `'value': 0` key actually

**Comment by Daenyth** [comment]
It might be possible to support the workflow with fewer code changes if `--action` could be used with other flags. As it, doing something like `punch --action bump --part beta` seems to run the action and then ignore the `part` flag

**Comment by lgiordani** [comment]
Hi! Your proposal is very interesting. I was actually considering moving everything in punch to actions (i.e. making the standard --part and friends actions themselves), so I'll gladly consider any contribution. Perhaps you could start splitting your proposal in smaller parts, so that it is easier to review them and to consider the direction to take.

One thing I really want to have are tests, please. So if you add some code first add a test that exposes the missing feature, if possible. If it is not possible, let's talk about it, there is always room for exceptions.

In the meanwhile I'll review what you wrote and start thinking at possible solutions. Thanks!

**Comment by Daenyth** [comment]
Thank you for the feedback, it makes sense.

Then to break things down:
- Add an action type corresponding to `--part`
- Add an action type corresponding to `--set-part`, for now with hardcoded value. Perhaps later the value can be determined by a function, as in `{'action_type': 'set_part', 'get_value': my_get_value_function}`. But for now hardcoded value is simpler (it would cover the "remove optional fragment" case).
- Add an action that collects a list of other actions to perform in sequence.
- Extend conditional_reset action to support multiple fields

I think all of those proposals could be implemented independently of each other. Do you agree?

**Comment by lgiordani** [comment]
Hey, just to say that I did not forget your proposal and I just started working on it. Sorry for ignoring the thread for so long. I will keep it updated with the progress of the feature

**Comment by Daenyth** [comment]
No worries. I haven't had time to work on many PRs lately either

**Comment by lgiordani** [comment]
Hey, if you are interested there is some development going on here https://github.com/lgiordani/punch/tree/feature/migrate-to-actions, feel free to check and give suggestions. It's still a preliminary version, so expect a lot of messy code :stuck_out_tongue:

**Comment by Daenyth** [comment]
A WIP PR would be easier to comment on, if you like

**Comment by lgiordani** [comment]
Here we are, #26 is ready to be reviewed. Sorry for the delay and thanks for the help

**Comment by lgiordani** [comment]
Hey, well, maybe 1.5 years later I can start addressing forgotten issues... Can you please check this and tell me what is missing in Punch from your initial request? Sorry for the delay!

**Comment by Daenyth** [comment]
I'm afraid I'm not currently working on any python projects and I don't recall much about the original context

**Comment by lgiordani** [comment]
Ok @Daenyth, I'm very sorry this took ages. Well, I think this PR already resulted in some good additions. So, for the time being, I'm going to close this. The `multi` action is on my list, anyway. Thanks for the help!
