### ISSUE TITLE
Print a warning when no match is found in controlled files

### ISSUE THREAD

**Issue by Daenyth** [lgiordani/punch#23]
I came across an issue where I `git reset --hard origin/master` on a branch which had changes to files listed in `FILES`, and then running punch after that only updates `punch_version.py`, and doesn't update the files. I'm wondering if it's using modification time or some other stat on the files to skip updating?

**Comment by Daenyth** [comment]
I tried using `touch -am` on my FILES and it still doesn't update them.

If I manually update the files, then subsequent calls seem to work as intended

**Comment by Daenyth** [comment]
Ok, I see - my punch_version.py file didn't match my FILES files, so the replacer couldn't find what to replace. A warning being printed in this case would be good.

**Comment by lgiordani** [comment]
Sorry for the late answer. I see the problem from what you just posted. I'll work on a warning, then. Thanks!

**Comment by lgiordani** [comment]
Solved in version 1.4.3. Now punch prints a warning for files that have not been updated
