### ISSUE TITLE
version regex match to IP addr

### ISSUE THREAD

**Issue by emcek** [lgiordani/punch#24]
Hi,
in my code **checker.py** I have:

```python
__version__ = '0.1.2'

class Checker():
    def __init__(self):
        self.ran = Bss(addr='10.0.1.2')
```

**punch_config.py**:
``` python
__config_version__ = 1
GLOBALS = {
    'serializer': '{{major}}.{{minor}}.{{patch}}',
}
FILES = ['checker.py', 'setup.py']
VERSION = ['major', 'minor', 'patch']
```
**punch_version.py**:
``` python
major = 0
minor = 1
patch = 2
```
When I run: 
```
# punch -p patch
```
 `addr` parameter will be change to **10.0.1.3**, what is of course is unacceptable. 
Is there any workaround of solution for it? 

Of course I can review all changes before commit, but lately I miss one place and spent 2h with debugger to find out, that punch did it ;)

**Comment by lgiordani** [comment]
Well, this is an unlucky case! You can consider changing your `serializer` to
```
GLOBALS = {
    'serializer': "__version__ = '{{major}}.{{minor}}.{{patch}}'",
}
```

which should do the job. You can also change it only for the `checker.py` file, as shown here http://punch.readthedocs.io/en/latest/ in the `FILES` section. You can have something like this:

```
GLOBALS = {
    'serializer': '{{ major }}.{{ minor }}.{{ patch }}'
}

FILES = [
    'version.txt',
    {
        'path': 'mypkg/__init__.py',
        'serializer': '{{ major }}.{{ minor }}'
    }
]
```

and the serializer will be overridden for that file.

Let me know if this solves the issue!

**Comment by emcek** [comment]
original **punch_config.py**:
``` python
__config_version__ = 1
GLOBALS = {
    'serializer': '{{major}}.{{minor}}.{{patch}}',
}
FILES = ['env_checker/checker.py', 'setup.py']
VERSION = ['major', 'minor', 'patch']
```
try change to:
``` python
__config_version__ = 1
GLOBALS = {
    'serializer': '{{major}}.{{minor}}.{{patch}}',
}
FILES = [
    'env_checker/checker.py',
    {
        'path': 'env_checker/checker.py',
        'serializer': "__version__ = '{{major}}.{{minor}}.{{patch}}'",
    },
    'setup.py'
]
VERSION = ['major', 'minor', 'patch']
```
and both __version__ and addr are changed.

1. I don't really get it what is a difference (in your example) between **version.txt** and  **mypkg/__init__.py**
2. Basicly I need in **env_checker/checker.py** use *\_\_version\_\_ = {{major}}.{{minor}}.{{patch}}* and in **setup.py** just *{{major}}.{{minor}}.{{patch}}*

**Comment by lgiordani** [comment]
Ok, if both are changed definitely there is an issue :)

In my example the difference between `version.txt` and `mypkg/init.py` is that the former uses `'{{ major }}.{{ minor }}.{{ patch }}'` as a serializer (which is the pattern used to match and to replace the version) while the latter uses `'{{ major }}.{{ minor }}'`.

You have to remove `'env_checker/checker.py'` from the `FILES` dictionary, otherwise Punch will use on it both the `GLOBALS` serilizer (incorrectly changing the address) and the specialised `FILES` serializer (correctly changing the version).

Let me know if it works and if the explanation is clear!

**Comment by emcek** [comment]
Oooooo.. I see

``` python
__config_version__ = 1
GLOBALS = {
    'serializer': '{{major}}.{{minor}}.{{patch}}',
}
FILES = [
    {
        'path': 'env_checker/checker.py',
        'serializer': "__version__ = '{{major}}.{{minor}}.{{patch}}'",
    },
    'setup.py'
]
VERSION = ['major', 'minor', 'patch']
```
did the job! Thx to be patient.

**Comment by lgiordani** [comment]
No problem at all!
