### ISSUE TITLE
Feature Request: Choose line ending

### ISSUE THREAD

**Issue by climbit** [lgiordani/punch#28]
Would it be meaningful to implement an option, where one can choose the line ending character?

greetings, Daniel

**Comment by lgiordani** [comment]
Hey, thanks for your contributions. May you please briefly describe your use case, so we may discuss if there are good reasons to introduce this feature? Thanks!

**Comment by climbit** [comment]
thanks for the warm welcome :)

I have to use windows at work but prefer linux at home, so if I work from home I always have to adapt the line ending before I commit.

**Comment by emcek** [comment]
git itself convert line endings. If you clone repo into windows git will change line endings to windows and when you commit will back on the fly change them to Linux. During installation of git in widows it ask you what to do. This is default recommended behavior.

**Comment by lgiordani** [comment]
@emcek Thanks for the useful insights. @climbit Please try it and report back if you think it is enough to cover the needs of Windows users.

**Comment by climbit** [comment]
Hi all,

the .gitattributes is a great way to handle line endings. It is very easy to introduce, as one just need to create the .gitattributes file with '* text'. Afterwards all files are normalized with LF during commit and checkout as is. 
Drawback: One rely on the git magic layer for text/binary detection.
If you don't want that, you have to specify every file type explicitely.

Apart from that, I realized, that it is the same for other tools and it seems, that there is no easy way to choose the line ending yourself in python. As far as I understood it would be neccessary to open the file in binary mode and replace the line ending character.

Therefore it seems the best solution to use .gitattributes for now.

Thanks for the open discussion,
Greetings,
Daniel
