### ISSUE TITLE
Add to simulation if version branch will be created or not

### ISSUE THREAD

**Issue by climbit** [lgiordani/punch#30]
Hi all,

I would like to see within the simulation:
 * Will version branch be generated
 * Will tags be annotaded
 * Which message will be attached to the tag

Is that meaningful?

Thank you,
Daniel

**Comment by lgiordani** [comment]
Yes I think this can be easily done, I'll work on it. Thanks for the submission

**Comment by lgiordani** [comment]
Hi! Can you please check if version 1.6.0 implements what you asked for? Thanks
