### ISSUE TITLE
[git VCS] Additional branch options

### ISSUE THREAD

**Issue by joshua-s** [lgiordani/punch#34]
It would be great if the git VCS could support the following:
- [x] Custom base branch:
    - Sometimes, releases need to be merged to a different branch than `master`
- [ ] Auto merge disabling with `make_release_branch` enabled:
    - Allows one to make changes, e.g. `HISTORY.rst` before finishing a release
    - Status checks (CI, coverage, etc) on protected branches block direct merges

**Comment by joshua-s** [comment]
I think I'll work on a PR for the first one.

**Comment by joshua-s** [comment]
I opened a PR for the first feature at #36

**Comment by lgiordani** [comment]
Thanks! As soon as you add the tests (tests BEFORE, man! :joy_cat: ) I'll review and merge. I think it should be enough to add a test in the `vcs_repositories` and one in `script`.
Thanks for the contribution!!

**Comment by lgiordani** [comment]
I'll soon release the version that contains your change. Thanks again.
As for the auto merge I like the idea and I will implement the flag (or accept PRs :wink:). I'm still looking for a good solution for the `HISTORY.rst` file and similar things. I'd like to have punch manage the whole workflow, so maybe I could implement something like a 2 step process that doesn't merge but then allows you to finish the release.

**Comment by lgiordani** [comment]
I just released version 1.5.0 that contains your fix. Thank you very much!

**Comment by lgiordani** [comment]
Hi! I'm working on the release notes (HISTORY) feature, so that will be available soon. Can you please clarify your last request relative to status checks? Thanks!

**Comment by lgiordani** [comment]
Hi, I opted for a solution that doesn't interrupt the flow, so I don't have to leave Punch in a half baked state, I will release it soon with version 2.0.0. I hope this can solve the issue with HISTORY files you pointed out (I was experiencing the same). If it doesn't, feel free to open a new issue. Thanks!

**Comment by joshua-s** [comment]
Hey @lgiordani I am very sorry. I totally missed this comment.

**Comment by joshua-s** [comment]
Thank you for the update. My comment on status checks did not involve any work from you; it was just highlighting a situation where being able to disable auto-merge would be useful.

**Comment by lgiordani** [comment]
Thanks for the clarification. I still have it in the TODO list, I will re-check to see if this is possible/reasonable to have. If you want to submit another issue specific to that, however, feel free, we can discuss it there. Thanks!
