### ISSUE TITLE
simulation, not existing file

### ISSUE THREAD

**Issue by climbit** [lgiordani/punch#35]
If a file is renamed, the simulation shows everything ok but if punch is executed it fails.
Therefore a check would be great.
If the check shows that the file is not existing, no file should be updated otherwise it will become inconsistent.
And it should also be shown within the simulation.

**Comment by lgiordani** [comment]
Hi, I'd like to have a better description of this issue, if possible, otherwise I don't know how to replicate the problem. Thanks!

**Comment by lgiordani** [comment]
I am going to close this because of the lack of proper testing data/information. Sorry
