### ISSUE TITLE
Why use punch instead of bumpversion?

### ISSUE THREAD

**Issue by kierun** [lgiordani/punch#6]
Title says it all really. Just curious, nothing nefarious implied by the question.

**Comment by lgiordani** [comment]
Thanks for the question. Bumpversion is basically an unmaintained project, unfortunately the author is no more active and many issues and PRs are sitting there waiting to be implemented. I had a lot of code I wanted to implement in bumpversion and the author was willing to move in that direction. But, as a matter of fact, the development does not progress, and I had many projects where I used a personal branch of bumpversion (which is not suitable but for a short span of time). So I tried to give my contribution with a project of mine. I have no complaints against bumpversion or its author, just a desire to share with the community a maintained project. I hope you will find it useful.

**Comment by kierun** [comment]
Yes, that's great!

Might I suggest adding the above (or something like it) to the README file?

**Comment by lgiordani** [comment]
Thanks, I'll consider it!
